language: ruby
rvm:
  - 2.1

cache: bundler

script: ./scripts/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - DISABLE_WHITELIST=true
    - MEDIUM_USER_ID=test
    - MEDIUM_INTEGRATION_TOKEN=test
    - MEDIUM_ENTITY=test

sudo: false
