language: ruby
cache: bundler
rvm:
  - 2.3.4
  - 2.4.1
matrix:
  include:
  allow_failures:
    - rvm: 2.4.1
  fast_finish: true
install:
  - travis_retry bundle install
before_script:
  - bundle exec jekyll build
  - pwd
  - ls
  - ls ..
    #- bundle exec htmlproofer . --only-4xx --assume-extension --check-favicon --check-html --allow-hash-href
script:
  - bundle exec rake site:deploy # --quiet

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
    - GIT_NAME=Travis CI
    - GIT_EMAIL=deploy@travis-ci.org
