language: ruby
rvm:
  - 2.1

cache: bundler

script: ./scripts/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - MEDIUM_USER_ID=test
    - MEDIUM_INTEGRATION_TOKEN=test
    - MEDIUM_ENTITY=test
    - secure: 1x/nptD+uWsjyoo2VXdOeyQTyWGHY0iXsls/KTE9b5WfBuDw6cQTmONHY0FST4TTZAUlx1jtIGEVV7WakL3N9J2k6SGi7JE2UARS9NPZNE+UqPZGiMPR6dKTbAR3XCRxA/eeceQXnUo7X4VdtsF6KB7b0rv9tg6FbjnIxgT3rHq8PcdV9fbur5+S4jl3fi1CCxTzHpoBQcSoSLMzjZEU3aFZFyCB7i8xiz0W9Z/05F4gs2sxQgDNBQx0jkO0z9WK+BTyet1lsTs/CEF0yfUAEmi1zQ4UUgAf/hcQ4MV1jO26K9a6YfG2HgE/xfO7CT7Hg0cQIfUBjPlCIaClLkZ+g2lCmJW14AtW8C1hiEfNB6BFBIZ3bKKQQu0+H71FOK2Z5GZeAxfx5WAupc6qVJGakEwd05ulSz0DmmjCIxfd+vOaZi/JoWQ1peqb6Y0ATaLgNPtrDgHJlPQGWN8vsWvTMrdjqfzdlOusrw22OAAA3YMMmVwfGa8SoQ8l4xjawfNRnOPPKnOo87up6qrmhnDriHfIcsMN1lZwHUWsvmGWzd7agEp9m4nDkA3MKWOGUnwv1pM+ee4TDgbgm1Tq/pARjFOwvHhcnI5m9IXpWumvqtX3CGnfKmi2ibVi9P//sH33kbAsRxgmquIEF94jMSn0qg7wynj13pcj0KvG647GUr8=
    - secure: qksDcG2cS+bNkX2RHWn2oddz/BQYGBq2Uu/xWybc2dYaZpBXSQi6LvgybB1glnAFAcIRA8aPGzuo4DzoBDufs2QMSnJNLMwGEwew5dIG16EDeXtnfGUeTBO6sH7no+CvIIqxHbBr/VSBYkNbymmoNV6kj07xQ+G+JntoIByfYYosFrI9k/KAyfDc7u5FU90PuMvlGXaYDSbMR8IfP34ndYawocF7+CQt40CkflRtkyayZLw3GODwnj7PgHJ5hDYznf9NzoQqECZIUGQxYmm+AWV/tHiUiHoj/u5HjuqKA4TPYqnrvYBJJmDflRjHkF8f9j7AjRG0H9gAEO3aymrCdb1Aa+e7Orc4t7IyoLArwIef/ip29OPHUoZ36R/dGW4ecRO4DoLnXmHZr1CaBCy0tYxwqzqcqSXF6Vk5Sdvp+AyVdEByi7VGeKbV1dYiXlriKtWN5H68JmQh/qUCMGqS7mgmfZc1LeqGhSlo0/D1O0IgyHsbl+Xfq5NMFXajXunLRseUFYQpM+Xq7+NjJlfrczN46lTigrUk70Diuv0fFqQgkwt8KheSmhwhWOBZJfusCIyxgAGm+8XtheRlyvBfgMS1sjNu1XDGv/XPI1kKRejlBlQqP6Buz9tD6T5KOdWk0ttnyjEK9dgqEKzm/zDhcZnMkQwVFABiHUv0u1weIT8=

sudo: false

after_success:
            'cd _site; find -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://teo-soft.com/terremotocentroitalia/{}'
