title: Janusz Nowak
email: janono@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jnowwwak
github_username: janusznowak
search: true
locale: en

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: PL
breadcrumbs: true

minimal_mistakes_skin: dirt

include:
- _pages
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jemoji
- jekyll-include-cache

author:
  name: Janusz Nowak
  avatar: https://avatars1.githubusercontent.com/u/5168275
  bio: bio.
  location: Warszawa, PL
  links:
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/janono/
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/jnowwwak
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/janusznowak
  - label: Facebook
    icon: fab fa-fw fa-facebook
    url: https://www.facebook.com/jnowwwak

footer:
  links:
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/janono/
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/jnowwwak
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/janusznowak
  - label: Facebook
    icon: fab fa-fw fa-facebook
    url: https://www.facebook.com/jnowwwak

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    classes: wide
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
    classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: disqus
  disqus:
    shortname: janono

analytics:
  provider: google
  google:
    tracking_id: UA-141219604-1
    anonymize_ip: false
