title: Sanchez Parra Labs Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frsanchez.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Francisco Sanchez
author-img: avatar.jpg
about-author: I am a full stack developer. Always learning and always improving.
social-twitter: tng2000
social-facebook: TimesFacts
social-github: frsanchez
social-linkedin: franciscodsanchez
social-email: sanchezparralabs@outlook.com
social-pinterest: franciscodsanch

# Disqus
discus-identifier:  # add your discus identifier

sass:
  style: :compressed # You might prefer to minify using :compressed

# Tracker
analytics: UA-156236534-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
