#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Disrupting Industries

# Short bio or description (displayed in the header)
description: Expatrié avant la fin de mes études, j'ai vécu un retour au pays mouvementé il y a un peu plus de 5 ans. Pas de réseau, profil inadapté, prétentions salariales sans lien avec la réalité, mon retour en France a été une vraie descente aux enfers. Pour survivre j'ai rangé mon égo, et pris des postes d'opérateur dans l'industrie. 

Au fil des mois j'ai découvert un système fortement dysfonctionnel, au sein duquel chaque jour se renforce le mur qui sépare l'opérationnel du management.

Plutôt que de rester dans mon coin, je suis devenu consultant en optimisation managériale. Depuis 3 ans je sillonne les routes pour casser ce mur et reconstruire une relation "gagnant-gagnant". Ce blog est là pour ceux que je ne pourrai pas aider, faute de temps.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow:
  youtube:
  googleplus:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://DisruptingIndustries.github.io/DisruptingIndustries.github.io)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/DisruptingIndustries.github.io"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
