safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "IRIS"
description: "怕什么真理无穷，得一寸有一寸的欢喜！"
baseurl: ""
url: "http://blog.dzq.tech" # replace by your site's url
twitter_username: your-name
github_username:  dzqoo
accent: "#f7f7e6" # accent color for blog column

author: "都真全"
address: "东北大学, <br>沈阳, 中国"
email: "dzq19910806@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
