# Site settings
title: Anurag Soni blog
email: 
description: “Data Scientist”
baseurl: ""
url: "https://anuragsoni9.github.io"
github_username:  anuragsoni9

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
