# Site settings
title: Miriam Tocino
email: miriam.tocino@gmail.com
description: "Turning into Web Developer"
author :
  name : Miriam Tocino
  email : miriam.tocino@gmail.com
  github : miriamtocino
  twitter : miriamtocino
  feedburner : feedname
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://miriamtocino.com" # the base hostname & protocol for your site
url: "http://www.miriamtocino.com" # the base hostname & protocol for your site
twitter_username: miriamtocino
github_username:  miriamtocino
pinterest_username:  miriamtocino
bitbucket_username:  miriamtocino
linkedin_username:  miriamtocino

# Build settings
# markdown: redcarpet
# redcarpet:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
permalink: /articles/:title
paginate: 10

# Navigation
navigation:
 - title: About
   url: /about.html
 - title: Projects
   url: /projects.html
 - title: Bookshelf
   url: /bookshelf.html
 - title: Elearning
   url: /elearning.html
 - title: Impressum
   url: /impressum.html