# Name of your site (displayed in the header)
name: Isard Miralles
webname: IsardMiralles.com

# Short bio or description (displayed in the header)
description: Il·lustració, Disseny i Música desde Badalona

google-top: Serveis professionals en Edició Web, illustració i Disseny gràfic desde Barcelona

# Oferta Web Portada
web: Edició Web
brand: Marca Corporativa
grafics: Grafísmes
music: Gestió Cultural

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/9498876?s=400&u=aee7e89c69bf3dee9903bc85ec6aa33985148325&v=4

phone: 658973617
serveis: Serveis
serveis-lead: Creatius, originals i fets a mà
portfoli: Creacions
portfoli-lead: Treballs destacats

# Web Prices
basica: 300
normal: 600
completa: 900
tenda: 900

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: isardmt@gmail.com
  facebook: Isard-Miralles-261219727225263
  flickr:
  github:
  behance:
  instagram: isardmiralles
  linkedin:
  pinterest:
  rss: rss
  twitter: isardmt
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: c/IsardMiralles
  googleplus: 

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-1636204-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://isardmiralles.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#


permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-redirect-from # Redirect www
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "assets/creations"
    values:
      image: true
