---
title: Rkalajian.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: A Pawn's Perspective
description: Toy and Game reviews, unboxings, and more.
avatar: https://secure.gravatar.com/userimage/204666/806084f3e9206b3e4cae74875d7bff5a?size=250
paginate: 8
footer-links:
  dribbble: 
  email: rkalajian@pawnsperspective.com
  facebook: pawnsperspective
  flickr: 
  github: 
  instagram: pawnsperspective
  linkedin: company/11005917
  periscope: perspectivepawn
  pinterest: pawnsperspectiv
  rss: rss
  twitch: rkalajian
  twitter: perspectivepawn
  stackoverflow: 
  youtube: channel/UCn0oN0SslDDS5Od5usgJ9fw
authors:
  robk:
    display_name: Rob Kalajian
    avatar: "/images/me.jpg"
    blurb: Father of 4. Husband to 1. Overall Geek. Rob is the owner of A Pawn's Perspective
      and an Editor over at Purple Pawn. During the day he's a Senior Web Developer
      for an ad agency in Avon, CT. In his free time...he has no free time. Games.
      Toys. Books. Scouting.
    email: rkalajian@pawnsperspective.com
    apage: "/about"
  frankg:
    display_name: Frank Grip
    avatar: "/images/frank.jpg"
    blurb: Frank is an attorney and family man currently based out of Las Vegas. He's
      a long time gaming enthusiast with a tabletop interest in most dungeon crawlers
      and map strategy games. If it has dice and minis, it probably has his attention.
    email: fgrip@pawnsperspective.com
    apage: "/author-frankgrip"
disqus: rck2
google_analytics: UA-383978-14
url: http://pawnsperspective.com
baseurl: ''
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-rss
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
