
# SEO settings
title: Рузэль Давлетяров
description: "Разработка под Bitrix."
keywords: "Разработка под Bitrix."
url: https://davletyarov.github.io
baseurl: ""
# baseurl: null
version: v0.5.4
google_analytics: UA-122243590-1
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: "https-davletyarov-github-io"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true


# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Рузэль Давлетяров
  job      : Разработчик
  bio      : "Рузэль Давлетяров - татарский программист"
  thumb    : /images/author.jpg
  email    : ovearub@gmail.com
  url      : https://davletyarov.github.io
  github   : https://github.com/davletyarov

# social settings
og_locale: "ru_RU"
timezone: Asia/Yekaterinburg

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
