# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Chad (Chungil Chae)
tagline:             'Workplace Data Analysis'
description:         'A reserved <a href="http://chadchae.github.io" target="_blank">Chad</a> Workplace Data Analysis. Made by <a href="https://twitter.com/chadchae" target="_blank">@chadchae</a>.'
url:                 http://chadchae.github.io
baseurl:             /
paginate:            

# About/contact
author:
  name:              Chad (Chungil Chae)
  url:               http://chadchae.github.io
  email:             chadchae@gmail.com

# Custom vars
version:             1.0.0
