#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Charles Rollins

# Short bio or description (displayed in the header)
description: baller since 02

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://image.winudf.com/123/9942279e63b647/icon=150x.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: 
  stackoverflow:
  youtube: 
  googleplus: 



disqus:


google_analytics:


url:





permalink: /:title/


version: v1.2.0
# Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
