# Site settings
title: Miriam Tocino
email: miriam.tocino@gmail.com
description: "Turning into Web Developer."
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://miriamtocino.com" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: miriamtocino
github_username:  miriamtocino

# Build settings
markdown: rdiscount
rdiscount:
    extensions: [smart]
permalink: /articles/:title
paginate: 3
