# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:              http://emeraldhieu.github.io

# Metadata
author:
  name:           Emerald Hieu
  url:            https://facebook.com/emerald.hieu

# Custom variables
version:          2.0.0
paginate:         5

# Name of your site (displayed in the header)
title: Emerald Hieu

# Short bio (displayed in the header)
tagline: Work Journal

# Description
description: "Do not go gentle into that good night"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/emeraldhieu.png?size=200
# profilePic: /public/images/profilePic.jpg

# Github
github:
  repo:           https://github.com/emeraldhieu/emeraldhieu.github.io

# Social network icons
footer-links:
  dribbble:
  email: emerald.hieu@gmail.com
  facebook: emerald.hieu
  flickr: 
  github: Emerald214
  instagram:
  linkedin: emeraldhieu
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: EmeraldHieu
  stackoverflow: users/238190/emerald214 # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/Emerald214 # channel/<your_long_string> or user/<user-name>
  googleplus: u/0/104884289048000944253 # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-90688567-1

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate # Pagination

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
