#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Shubham Ramdeo

# Short bio or description (displayed in the header)
description: geek

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/4460235?v=3&s=460

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: test
  email: ramdeo.shubham@gmail.com
  facebook: /ramdeo.shubham
  flickr: /photos/63735809@N05
  github: ramdeoshubham
  instagram: test
  linkedin: ramdeoshubham
  pinterest: ramdeoshubham
  rss: test
  twitter: ramdeoshubham
  stackoverflow: test
  youtube: user/ramdeoshubham
  googleplus: +ShubhamRamdeo


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: ramdeoshubham

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-47705353-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://ramdeoshubham.blogspot.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll No
