# Site settings
title: David Seo's Software Story
url: "http://shs11023.github.io"
baseurl: "/"
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: shs11023@gmail.com
author: David Seo
avatar: "//https://s.gravatar.com/avatar/49464e707e4a3b9c8de7be7e39289b6e?s=80"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
github_username:  shs11023

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
