title: Jordan Hanley (Web Application Developer)
description: > # this means to ignore newlines until "baseurl:"
  A personal blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jordan Hanley # add your name
author-img: jordan.png # add your photo
about-author: Developer, Problem Solver, Manager, Husband, Dad. I wear many different hats! # add description
social-twitter: jords1987
social-facebook: jordan.hanley.5
social-github: jords1987
social-linkedin: jordan-hanley-37691b93
social-email: jordanhanley87@gmail.com

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: G-61RDLKW0KM # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
