# Site settings
title: BananaStore
email: bananastore.help@gmail.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: ""
url: "http://bananastore.github.io"

author:
  name     : 'Gigwan Lee'
  email    : bananastore.help@gmail.com
  url      : http://bananastore.github.io
  facebook : 
  twitter  : 

github: http://bananastore.github.io
disqus_shortname: "BananaStore"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
