---
title: Rkalajian.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: A Pawn's Perspective
description: Toy and Game reviews, unboxings, and more.
avatar: https://secure.gravatar.com/userimage/204666/806084f3e9206b3e4cae74875d7bff5a?size=250
paginate: 8
footer-links:
  dribbble: 
  email: rkalajian@pawnsperspective.com
  facebook: pawnsperspective
  flickr: 
  github: 
  instagram: pawnsperspective
  linkedin: company/11005917
  periscope: perspectivepawn
  pinterest: pawnsperspectiv
  rss: rss
  twitch: rkalajian
  twitter: perspectivepawn
  stackoverflow: 
  youtube: channel/UCn0oN0SslDDS5Od5usgJ9fw
authors:
  robk:
    display_name: Rob Kalajian
    email: rkalajian@pawnsperspective.com
    apage: "/about"
  frankg:
    display_name: Frank Grip
    email: fgrip@pawnsperspective.com
    apage: "/author-frankgrip"
disqus: rck2
google_analytics: UA-383978-14
url: http://pawnsperspective.com
baseurl: ''
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-rss
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
