# Site settings
description: "O conhecimento que você precisa, do jeito que você quer!"
baseurl: ""
url: "http://blog.codeshare.com.br"
icon: https://raw.githubusercontent.com/CodeShareEducation/CodeShareEducation.github.io/master/src/img/icons/favicon.ico

# User settings
username: CodeShare Blog
user_description: O conhecimento que você precisa, do jeito que você quer!
user_title: O conhecimento que você precisa, do jeito que você quer!
user_gravatar: d36a082aacb53b6f76869748fb4b81d4
email: contact@codeshare.com.br
github_username:  CodeShareEducation
gplus_username: CodeshareBrEducation
twitter_username: codeshare_br
disqus_username: codeshareeducation

authors:
  wendell:
    name: Wendell Adriel
    gravatar: d36a082aacb53b6f76869748fb4b81d4
    email: contact@wendelladriel.com
    github: WendellAdriel
    linkedin: wendelladrielti/en
    twitter: wendell_adriel
    facebook: wendell.adriel.7
    site: http://wendelladriel.com
    bio: "Criador da CodeShare, Desenvolvedor Full Stack, Zend Certified PHP Engineer,
    Graduado em Análise e Desenvolvimento de Sistemas, Gamer, Baixista e baterista. Trabalho com desenvolvimento desktop
    e web desde 2009 e com desenvolvimento mobile desde 2015. Gosto de sempre aprimorar e atualizar meus conhecimentos e
    também trocar experiências e conhecimentos com os que estão à minha volta. Gosto de trabalhar com desenvolvimento
    Front-end e Back-end. Trabalho com diversas tecnologias e você pode conferir a lista completa de minhas skills em meu site pessoal."

  mcqueide:
    name: John Mc.Queide
    gravatar: cdb899949441a43c0479035ab5e5d5d9
    email: mcqueide@gmail.com
    github: mcqueide
    linkedin: mcqueide/en
    twitter:
    facebook:
    site:
    bio: "Sou Desenvolvedor Java, graduado em Análise e Desenvolvimento de Sistemas, possuo as certificações Java
    Programmer e Java Web Component Developer.
    Tenho 2 anos de experiência com desenvolvimento de software voltados para web. Gosto muito de ler, e compartilhar
    conhecimento com os que estão a minha volta, e estou sempre a procura de um maior crescimento."

  vinicius:
    name: Vinicius Oliveira da Silva
    gravatar: e2ed81a1a0937c3cc302caec8964ae49
    email: si.vinicius@hotmail.com
    github: sivinicius
    linkedin: sivinicius
    twitter:
    facebook: si.vinicius
    site: http://sivinicius.github.io
    bio: "Desenvolvedor Full Stack, Oracle Certified Java SE 8 Programmer I, graduado em Sistemas de Informação.
    Atuei em diversos projetos onde adquiri grande conhecimento em diversas linguagens, tecnologias e frameworks.
    Tenho foco em produtividade e qualidade de desenvolvimento de software e além de apaixonado por tecnologia tenho muito prazer em aprender e ensinar."

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categorias
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre
    url: /about
  - title: Site CodeShare
    url: http://codeshare.com.br
    external: true


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
