# Site settings
name: IRIS
email: dzq19910806@gamil.com
author: dzq
url: http://blog.dzq.tech
resume_site: #
github: https://github.com/dzqoo/
baseurl: ""
description: 怕什么真理无穷，得一寸又一寸的欢喜
meta_description: 都真全;个人博客;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: dzqoo
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : dzqoo
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light