#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Dactrtr

# Header Image
imgheader: /assets/build/blog.gif

# Short bio or description (displayed in the header)
description: 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/2884334?v=3&s=460
author:
    gravatar_md5:  78bb581d6e6e3ef3d75c78a57774c436
paginate: 8
#
# Flags below are optional
#
collections:
    projects:
        output: true
        
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: dactrtr@gmail.com
  facebook: 
  flickr: 
  github: dactrtr
  instagram: dactrtrs
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: dactrtr
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  behance: dactrtr


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: dactrtr

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: Pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
