markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
duoshuo: true
blog:
  name: "wang`s Blog"
  description: "Share with U"
  title: "iwang.me"
  url: "iwang.me"
  duoshuo: "mambablack.github.io"
author:
  name: "wang"
  email: "wang@126.com"
  weibo: "weibo.com"
  github: "mambablack.github.io"
  logo: "/res/img/logo/baymax.jpg"