#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Sangwan Kwon

# Short bio or description (displayed in the header)
description: Software Engineer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.abyul.com/zbxe/files/attach/images/1631/413/120/%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%86%A1_%EA%B8%B0%EB%B3%B8%EC%9D%B4%EB%AA%A8%ED%8B%B0%EC%BD%98_%EC%B9%B4%ED%86%A1%EC%9D%B4%EB%AA%A8%ED%8B%B0%EC%BD%98_07%ED%81%AC%ED%81%AC.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: bitboom9@gmail.com
  facebook:
  flickr:
  github: bitboom
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://bitboom.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
