# Site settings
title: Miriam Tocino
email: miriam.tocino@gmail.com
description: "Turning into Web Developer ♥"
author :
  name : Miriam Tocino
  email : miriam.tocino@gmail.com
  github : miriamtocino
  twitter : miriamtocino
  feedburner : feedname
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.miriamtocino.com" # the base hostname & protocol for your site
twitter_username: miriamtocino
github_username:  miriamtocino
pinterest_username:  miriamtocino
bitbucket_username:  miriamtocino
linkedin_username:  miriamtocino

# Build settings
permalink: /articles/:title
paginate: 3

# Navigation
navigation:
 - title: About
   url: /about.html
 - title: Archive
   url: /archive.html
 - title: Bookshelf
   url: /bookshelf.html
 - title: Elearning
   url: /elearning.html