title: Brain I/O
description: Let's talk about programming
show_downloads: true

baseurl: "/"
url: "https://alexwnovak.github.io"

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme:

author: "Alex Novak"
image: /thumbnail-jumbo.png
twitter:
  username: alexwnovak

plugins:
  - jekyll-gravatar
