title:              Jay Coder
email:
description:        Jay's Blog
author:             Jay Lin
baseurl:            "/"
url:                "https://jay-coder.github.io/"

# Social Profiles
twitter_username:   
github_username:    jay-coder
facebook_username:  
instagram_username:  
linkedin_username:  jaycoder

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-135437161-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
