# Site settings
title: "Joel Whitney"
email: whitney.joel.b@gmail.com
description: "Personal blog"
baseurl: ""
url: "https://joelwhitney.github.io"
title_description: "Software product engineering at <a href=https://esri.com>esri</a>.  My passions include hockey, craft beer, geospatial technology, data and software development. I'm enjoy building things, I'm better at breaking them."
title_image: "https://www.gravatar.com/avatar/3c1f1234d97343cd8e5766a73ed65d4a?s=500&d=mm"
google_analytics: ""
#disqus_account: joelwhitney
github_repository:
addthis_id:
personal_post_limit: 1
work_post_limit: 6

# Social usernames/URLs
twitter_username:
github_username:  JoelWhitney
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/joelwhitney/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM

permalink: pretty
exclude: [vendor]

highlighter: rouge

colors:
  orange:    '#fab125'
