# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Coding with Sutemi
tagline:          'Chris Phelps Blog'
description:      "Sutemi (n): The state of giving one's all, prepared even to give up one's life. Scala and other coding topics"
url:              http://chrisphelps.github.io
baseurl:          /

author:
  name:           'Chris Phelps'
  url:            https://twitter.com/CJPhelps

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/chrisphelps
