# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Manu Contreras
tagline:             'Desde Git'
description:         'Blog sobre tecnología, diseño y vida de Manu Contreras. Versión alojada en <a href="https://www.github.com">GitHub</a>.'
url:                 http://mcontreras.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Manu Contreras
  url:               https://twitter.com/mcontreras
  email:             manu@contreras.cc

# Custom vars
version:             1.0.0
