#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: A Pawn's Perspective

# Short bio or description (displayed in the header)
description: Tabletop gaming with a sprinkle of toys and video games.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://en.gravatar.com/userimage/204666/806084f3e9206b3e4cae74875d7bff5a.jpg?size=200

#
# Flags below are optional
#

#pagination

paginate: 8

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: rkalajian@gmail.com
  facebook: pawnsperspective
  flickr:
  github: rkalajian
  instagram: r_kalajian
  linkedin: rkalajian
  periscope: rkalajian
  pinterest: rkalajian
  rss: rss
  twitch: rkalajian
  twitter: rkalajian
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/rkalajian

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: rck2

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-383978-14

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://pawnsperspective.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate #pagination
  - jekyll-rss #RSS


# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
