# Site settings
title: "Joel Whitney"
email: whitney.joel.b@gmail.com
description: "Personal blog"
baseurl: ""
url: "https://joelwhitney.github.io"
title_description: "GIS software, spatial data anyalytics, and location intelligence at <a href=https://esri.com>esri</a>.  Develop software for iOS, macOS, and Python in my spare time."
title_image: "https://www.gravatar.com/avatar/3c1f1234d97343cd8e5766a73ed65d4a?s=500&d=mm"
google_analytics: ""
disqus_account: joelwhitney
github_repository:
addthis_id:
post_limit: 5
work_post_limit: 5

# Social usernames/URLs
twitter_username:
github_username:  JoelWhitney
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/joelwhitney/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
1: https://esri.com
