# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Manu Contreras
tagline:             'Desde el hipertexto'
description:         'Escribo sobre tecnología de consumo y tecnología móvil.'
url:                 http://mcontreras.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Manu Contreras
  url:               https://twitter.com/mcontreras
  email:             manu@contreras.cc

# Custom vars
version:             1.0.0
