#
###################################
# Site wide configuration
####################################
#
title:       "A Pawn's Perspective"
description: "A little depth into my tabletop hobby"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: A Pawn's Perspective
  avatar: avatar.png
  job: Robert C. Kalajian Jr.
  bio: A little depth into my tabletop hobby
  email: rkalajian@gmail.com
  disqus-shortname: rck2
  twitter: rkalajian
  facebook: rkalajian
  google:
    plus:
    analytics: UA-383978-14
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rkalajian
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: rkalajian
  xing: #username
  instagram: r_kalajian
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: rkalajian
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  twitch: rkalajian
  periscope: rkalajian
