#Settings
title: lightj
description: "Web DevBlog"
url: "http://lightj.github.io/"
baseurl: ""
markdown: redcarpet
highlighter: pygments
permalink: /:title/
sass:
  style:: expanded
  compressed: true
