# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            A Pawn's Perspective
tagline:          'A little depth to my tabletop hobby'
description:      'Items that don't fit the mold of my normal Purple Pawn posts'
url:              http://pawnsperspective.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
