#Settings
name: lightj
description: "Web DevBlog"
google_analytics: "UA-64331584-1"
url: "http://lightj.github.io/"
baseurl: ""
markdown: redcarpet
highlighter: pygments
permalink: /:title/
sass:
  style: :expanded # You might prefer to minify using :compressed
  compressed:true
