blog:
  # image: 'grahamc/jekyll'
  build: "."
  volumes:
    - ./:/src
  ports:
    - "4000:4000"
  command: ["serve", "--config", "_config.yml,_config_dev.yml", "-H", "0.0.0.0", "--incremental", "--drafts", "--force_polling"]
