version: 2
jobs:
  # Build job
  build:
    working_directory: &working_directory
      /tmp/iwe
    parallelism: 1
    # environment:
    #   CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    #   CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: jekyll/jekyll:builder
    steps:
      - checkout
      #- setup_remote_docker
      # - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      #- run: chmod 777 /tmp/iwe
      - run:
          # The circle host does some funny with the folder permissions ...
          name: Building Jekyll website
          command: |
            chmod 777 /tmp/iwe
            jekyll build --source /tmp/iwe --config /tmp/iwe/_config.yml --destination /tmp/iwe/build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - build
      # - run:
      #     name: Testing a blogposts!
      #     command: |
      #       bundle exec htmlproofer ~/infinityworks/engineering/build --allow-hash-href --check-favicon --check-html --disable-external --empty-alt-ignore | tee $CIRCLE_TEST_REPORTS/htmlproofer-results.txt
      #       #for file in $(find ~/infinityworks/engineering/build/ -name \*.html); do aspell -H $file; done
      # - store_test_results:
      #     path: /tmp/circleci-test-results

  # Deploy job - using WS to transfer the result of the build
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync ./build/ s3://${S3_ENGINEERING_BUCKET}/ --delete --exclude ".circleci/*"

  see:
    docker:
      - image: circleci/python:2.7
    working_directory: *working_directory
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: See-through
          command: ls -laR ./build


# And now plugging things together
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  build-see:
    jobs:
      - build
      - see:
          requires:
            - build
          filters:
            branches:
              only: upgrade-to-circle-2