title:              "코딩 블로그"
email:              "leejongho9803@gmail.com"
description:        "하위"
author:             Start Bootstrap
baseurl:            ""
url:                "https://JT-TT.github.io"
theme:              jekyll-theme-clean-blog

# Social Profiles
twitter_username:   
github_username:    JH-TT
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JH-TT"